/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import jp.ac.uryukyu.ie.e225733.*;

public class Main {
    public static void main(String[] args) {
        // コンピュータの答えをランダムに取得する。
        Suujiate comAnser = new Suujiate();
        int com = comAnser.getComAnswer();
        
        // 正解するまで何度でも繰り返す
        while (true) {
        
            // ユーザの予想値の取得
            Suujiate userGuess = new Suujiate();
            int user = userGuess.getUserGuess();
        
            // 正解/不正解のチェック
            Suujiate judge = new Suujiate();
            boolean jud = judge.isJudgeAnswer(com,user);

            // 正解の場合
            if (jud) {
            break; // 処理の終了
            }else { // 不正解の場合
            // 何もしない(次のループ)
            }
        }
    }
}
